const api = {
  prodDomain: 'http://127.0.0.1:6060',
  devDomain: 'http://127.0.0.1:6060',
  prodwsDomain: 'ws://127.0.0.1:6061/ws',
  devWsDomain: 'ws://127.0.0.1:6061/ws',
  checkCode: '/account/checkCode',
  login: '/account/login',
  register: '/account/register',
  search: '/userContact/search',
  apply: '/userContact/contactApply',
  contactNotice: '/userContact/loadContactApply',
  dealWithApply: '/userContact/dealWithApply',
  loadContact: '/userContact/loadContact',
  loadMyGroup: '/group/loadMyGroup',
  saveGroup: '/group/saveGroup',
  getGroupInfo: '/group/getGroupInfo',
  uploadImage: '/file/uploadImage',
  addContact2BlackList: '/userContact/addContact2BlackList',
  delContact: '/userContact/delContact',
  getUserInfoByUserId: '/userInfo/getUserInfoByUserId',
  getUserInfo: '/userInfo/getUserInfo',
  dissolutionGroup: '/group/dissolutionGroup',
  leaveGroup: '/group/leaveGroup',
  getContactInfo: '/userContact/getContactInfo',
  sendMessage: '/chat/sendMessage',
  sendMessageFile: '/chat/sendMessageFile',
  saveUserInfo: '/userInfo/saveUserInfo',
  saveSysSetting: '/admin/saveSysSetting',
  callCreate: '/call/create',
  callAccept: '/call/accept',
  callReject: '/call/reject',
  callCancel: '/call/cancel',
  callHangup: '/call/hangup',
  getCallInfo: '/call/getCallInfo',
  getRtcConfig: '/call/getRtcConfig'
}

export default api
